const data = [
    { name: "Bahrain Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/2.png" },
    { name: "Saudi Arabia Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/29.png" },
    { name: "Australia Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/1.png" },
    { name: "Emilia Romagna Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/27.png" },
    { name: "Miami Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/31.png" },
    { name: "Spain Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/6.png" },
    { name: "Monaco Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/7.png" },
    { name: "Azerbaijan Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/8.png" },
    { name: "Canada Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/9.png" },
    { name: "Great Britain Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/12.png" },
    { name: "Austria Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/11.png" },
    { name: "France Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/10.png" },
    { name: "Hungary Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/14.png" },
    { name: "Belgium Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/15.png" },
    { name: "Netherlands Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/5.png" },
    { name: "Italy Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/16.png" },
    { name: "Russia Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/18.png" },
    { name: "Singapore Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/17.png" },
    { name: "Japan Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/19.png" },
    { name: "USA Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/20.png" },
    { name: "Mexico Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/21.png" },
    { name: "Brazil Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/22.png" },
    { name: "Abu Dhabi Grand Prix", image: "https://media.api-sports.io/formula-1/circuits/23.png" },
]

export default data;